export function createBindingContext(state, handlers) {
  return {
    panel: state.panel,
    el: state.el,
    tabButtons: state.tabButtons,
    subTabButtons: state.subTabButtons,
    subTabPanels: state.subTabPanels,
    escBlurPending: state.escBlurPending,
    get codeDefaults() {
      return state.getCodeDefaults();
    },
    get storageKey() {
      return state.getStorageKey();
    },
    readConfigFromForm: handlers.readConfigFromForm,
    fillFormFromConfig: handlers.fillFormFromConfig,
    resetAnimProp: handlers.resetAnimProp,
    getTypeArray: handlers.getTypeArray,
    getMaskButtons: handlers.getMaskButtons,
    setStaggerAxis: handlers.setStaggerAxis,
    setStaggerTiming: handlers.setStaggerTiming,
    requestLiveUpdate: handlers.requestLiveUpdate,
    requestTypographyUpdate: handlers.requestTypographyUpdate,
    markSplitTextDirty: handlers.markSplitTextDirty,
    selectTab: handlers.selectTab,
    selectSubTab: handlers.selectSubTab,
    setPanelOpen: handlers.setPanelOpen,
    isPanelOpen: handlers.isPanelOpen,
    runFullRebuild: handlers.runFullRebuild,
    commitAndRebuild: handlers.commitAndRebuild,
    exportTypographyCss: handlers.exportTypographyCss,
    switchToInstance: handlers.switchToInstance,
    setFollowViewportEnabled: handlers.setFollowViewportEnabled,
    onResetAll: handlers.onResetAll,
    onApplyImport: handlers.onApplyImport,
    isActive: state.isActive,
    getInstanceList: state.getInstanceList,
    getActiveInstanceId: state.getActiveInstanceId,
    getImportDrawerOpen: state.getImportDrawerOpen,
    setImportDrawerOpenState: handlers.setImportDrawerOpenState,
    getConvertedImportConfig: state.getConvertedImportConfig,
    setConvertedImportConfig: handlers.setConvertedImportConfig,
    getImportWarnings: state.getImportWarnings,
    setImportWarnings: handlers.setImportWarnings,
    setCodeDefaults: handlers.setCodeDefaults,
    setWorkingConfig: handlers.setWorkingConfig,
    setCommittedConfig: handlers.setCommittedConfig,
    setTypographyDirty: handlers.setTypographyDirty,
    setSplitTextDirty: handlers.setSplitTextDirty,
    setPendingUI: handlers.setPendingUI,
  };
}
