export const SCROLL_TRIGGER_ZODIAC_NAMES = [
  {
    sign: "Aries",
    element: "fire",
    api: "start",
    name: "The Ram's Threshold",
    flavor: "First fire sign — the moment scroll crosses the opening gate",
  },
  {
    sign: "Taurus",
    element: "earth",
    api: "pin",
    name: "The Bull's Hold",
    flavor: "Fixed earth — element locked in place while the world scrolls on",
  },
  {
    sign: "Gemini",
    element: "air",
    api: "onToggle",
    name: "The Twin Gates",
    flavor: "Dual nature — active/inactive, play/pause, forward/backward",
  },
  {
    sign: "Cancer",
    element: "water",
    api: "onEnterBack",
    name: "The Returning Tide",
    flavor: "Moon-ruled retreat — scrolling back into the trigger zone",
  },
  {
    sign: "Leo",
    element: "fire",
    api: "markers",
    name: "The Lion's Beacon",
    flavor: "Solar spotlight — dev markers illuminating start/end in the viewport",
  },
  {
    sign: "Virgo",
    element: "earth",
    api: "snap",
    name: "The Virgin's Alignment",
    flavor: "Mutable earth precision — snapping to exact progress points",
  },
  {
    sign: "Libra",
    element: "air",
    api: "scrub",
    name: "The Scales in Drag",
    flavor: "Cardinal air balance — animation catching up to scroll position",
  },
  {
    sign: "Scorpio",
    element: "water",
    api: "getVelocity",
    name: "The Sting of Velocity",
    flavor: "Fixed water intensity — reading scroll speed at the moment of strike",
  },
  {
    sign: "Sagittarius",
    element: "fire",
    api: "direction",
    name: "The Archer's Bearing",
    flavor: "Mutable fire — forward (1) or backward (-1) scroll heading",
  },
  {
    sign: "Capricorn",
    element: "earth",
    api: "end",
    name: "The Mountain's Limit",
    flavor: "Cardinal earth summit — the terminal scroll position",
  },
  {
    sign: "Aquarius",
    element: "air",
    api: "batch",
    name: "The Constellation Batch",
    flavor: "Fixed air collective — many triggers firing as one coordinated group",
  },
  {
    sign: "Pisces",
    element: "water",
    api: "scroller",
    name: "The Neptunian Current",
    flavor: "Mutable water flow — the scroll container beneath everything",
  },
];
