import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const FONTS_DIR = __dirname;
const OUTPUT = join(__dirname, "../css/fonts.css");

const EXTENSIONS = new Set([".woff2", ".woff", ".otf", ".ttf"]);

/** Only ASCII letters, digits, dots, underscores, hyphens — safe for URLs without encoding */
const SAFE_FILENAME = /^[A-Za-z0-9._-]+\.(woff2|woff|otf|ttf)$/;

/** OpenType axis tokens in filenames (e.g. Geist[wght].woff2) — skip; use static cuts instead */
const VARIABLE_AXIS_IN_NAME = /\[[a-z]+\]/i;

const WEIGHT_MAP = [
  ["extralight", 200],
  ["ultralight", 200],
  ["thin", 100],
  ["light", 300],
  ["book", 400],
  ["regular", 400],
  ["medium", 500],
  ["semibold", 600],
  ["bold", 700],
  ["extrabold", 800],
  ["ultrabold", 800],
  ["black", 900],
];

function slugToFamilyName(slug) {
  return slug
    .split("-")
    .map((part) => {
      if (part === "fh") return "FH";
      if (part === "kh") return "KH";
      if (part === "pp") return "PP";
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join(" ");
}

function parseWeightAndStyle(filename) {
  const base = filename.replace(/\.[^.]+$/, "");
  const lower = base.toLowerCase();
  const style = /italic/.test(lower) ? "italic" : "normal";

  let weight = 400;
  for (const [token, value] of WEIGHT_MAP) {
    if (lower.includes(token)) {
      weight = value;
      break;
    }
  }

  return { weight, style };
}

function shouldIncludeFont(filename) {
  if (VARIABLE_AXIS_IN_NAME.test(filename)) {
    return { ok: false, reason: "variable-axis filename (e.g. [wght])" };
  }
  if (!SAFE_FILENAME.test(filename)) {
    return {
      ok: false,
      reason: "filename must be ASCII [A-Za-z0-9._-] only (no spaces or special characters)",
    };
  }
  return { ok: true };
}

async function collectFontFiles(dir, files = []) {
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      await collectFontFiles(fullPath, files);
    } else if (EXTENSIONS.has(entry.name.slice(entry.name.lastIndexOf(".")).toLowerCase())) {
      files.push(fullPath);
    }
  }

  return files;
}

async function main() {
  const allFiles = await collectFontFiles(FONTS_DIR);
  allFiles.sort();

  const skipped = [];
  const fontFiles = [];

  for (const filePath of allFiles) {
    const filename = filePath.split("/").pop();
    const check = shouldIncludeFont(filename);
    if (check.ok) {
      fontFiles.push(filePath);
    } else {
      skipped.push({ path: relative(FONTS_DIR, filePath), reason: check.reason });
    }
  }

  const families = new Set();
  const faceBlocks = [];

  for (const filePath of fontFiles) {
    // css/fonts.css → ../fonts/{family}/{file}
    const relFromOutput = join("..", "fonts", relative(FONTS_DIR, filePath)).replace(
      /\\/g,
      "/",
    );
    const parts = relFromOutput.split("/");
    const slug = parts[parts.indexOf("fonts") + 1];
    const filename = parts[parts.length - 1];
    const familyName = slugToFamilyName(slug);
    const { weight, style } = parseWeightAndStyle(filename);

    families.add(slug);

    faceBlocks.push(`@font-face {
  font-family: "${familyName}";
  src: url("${relFromOutput}") format("${getFormat(filename)}");
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}`);
  }

  const sortedFamilies = [...families].sort();
  const rootVars = sortedFamilies
    .map((slug) => `  --font-${slug}: "${slugToFamilyName(slug)}", sans-serif;`)
    .join("\n");

  const css = `/* Generated by generate-fonts.mjs — do not edit by hand */
/* ${fontFiles.length} @font-face declarations (${skipped.length} skipped) */

${faceBlocks.join("\n\n")}

:root {
${rootVars}
}
`;

  await writeFile(OUTPUT, css, "utf8");
  console.log(`Wrote ${fontFiles.length} @font-face rules to fonts.css`);

  if (skipped.length > 0) {
    console.warn(`Skipped ${skipped.length} font file(s):`);
    for (const { path, reason } of skipped) {
      console.warn(`  - ${path}: ${reason}`);
    }
  }
}

function getFormat(filename) {
  const ext = filename.slice(filename.lastIndexOf(".")).toLowerCase();
  if (ext === ".woff2") return "woff2";
  if (ext === ".woff") return "woff";
  if (ext === ".otf") return "opentype";
  return "truetype";
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
